### ISSUE TITLE
Support running a specific version

### ISSUE THREAD

**Issue by keverw** [bluelovers/ws-ypx#7]
I was following a tutirual but since I nuked NPM off my system was looking up the Yarn equivalent and found this CLI tool. So I swapped npx for ynpx.

`ynpx create-nx-workspace@latest`

I got a command not found.... Changed it to:

`ynpx create-nx-workspace`

and Yay! It installs...

So I think being able to optionally fetch a specie version could come in handy.

**Comment by bluelovers** [comment]
done

u can try

```
ynpx cowsay@latest -- test
```

**Comment by keverw** [comment]
Thanks! That was fast. Could see that coming in handy in the future.

**Comment by bluelovers** [comment]
@keverw already publish new version
